AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: P1
Resources:
  A3b1website:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: b2phtos
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e1e00b0a-5f39-48e8-bb88-1032cec330f4
  A3b2photostore:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: b1phtos
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 553d59a4-4938-412e-99d9-37ae122b8e4a
  A3L2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: A3L2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LF2
      Description: LF2
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:lambda:us-west-2:224019584573:function:search-photos'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search
            Method: post
      Environment:
        Variables:
          REGION: us-west-2
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 87778e30-ba4d-4b4d-8cba-35e1923e76af
  A3L1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: A3L1
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./LF1
      Description: LF1
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:lambda:us-west-2:224019584573:function:index-photos'
      Environment:
        Variables:
          REGION: us-east-1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: dd301049-1809-4426-8143-c8b1be328538
  A3L3:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: A3L3
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda_function_3.py
      Description: LF3
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::098015424271:role/service-role/upload_to_s3-role-9x78khho'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /uploadimage
            Method: put
      Environment:
        Variables:
          REGION: us-east-1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2dfa35b0-9b5a-4f30-bc3b-06b4a4f5b1fa
  ElasticsearchDomain:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      DomainName: photoboot
      ElasticsearchVersion: '7.4'
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: 'false'
        InstanceCount: '2'
        ZoneAwarenessEnabled: 'true'
        InstanceType: t3.small.elasticsearch
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: gp2
      SnapshotOptions:
        AutomatedSnapshotStartHour: '0'
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: 'arn:aws:es:us-west-2:224019584573:domain/photoboot/*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5cd27639-db97-49cf-adcb-7cb02f3879a7
Metadata:
  'AWS::CloudFormation::Designer':
    5cd27639-db97-49cf-adcb-7cb02f3879a7:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    2dfa35b0-9b5a-4f30-bc3b-06b4a4f5b1fa:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
    dd301049-1809-4426-8143-c8b1be328538:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 210
      z: 1
      embeds: []
    87778e30-ba4d-4b4d-8cba-35e1923e76af:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 210
      z: 1
      embeds: []
    553d59a4-4938-412e-99d9-37ae122b8e4a:
      size:
        width: 60
        height: 60
      position:
        x: 290
        'y': 90
      z: 1
      embeds: []
    e1e00b0a-5f39-48e8-bb88-1032cec330f4:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 210
      z: 1
      embeds: []
